In [65]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler
from tensorflow.keras.regularizers import l2
from tensorflow.keras.datasets import mnist
import numpy as np
import pandas as pd

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train/255., X_test/255.
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

hnode_list = [10,128]
lambda_ = 1
epoch = 30
batsize = 32
patience = 20
ES_mon = 'val_loss'

results = pd.DataFrame()

for hnode in hnode_list:
    loss_list = []
    acc_list = []
    
    model_DNN = Sequential()
    model_DNN.add(Flatten(input_shape=(28,28)))
    model_DNN.add(Dense(hnode, activation='relu', kernel_initializer='he_normal'))#, kernel_regularizer=l2(lambda_), bias_regularizer=l2(lambda_)))
    model_DNN.add(Dense(10, activation='softmax',))# kernel_regularizer=l2(lambda_), bias_regularizer=l2(lambda_)))
    model_DNN.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics='acc')
    
    ES_CB = EarlyStopping(monitor=ES_mon, patience=patience)
    MC_CB = ModelCheckpoint('C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습/{}'.format(hnode), monitor='val_loss', verbose=0, save_best_only=True)

    model_DNN.fit(X_train,y_train, validation_data=(X_test,y_test), verbose=0, batch_size=batsize, epochs=epoch, callbacks=[ES_CB,MC_CB])
    print(model_DNN.summary())

    loss, acc = model_DNN.evaluate(X_test,y_test)
    loss_list.append(loss)
    acc_list.append(acc)
    avg_acc = np.mean(acc_list)
    avg_loss = np.mean(loss_list)
    print (avg_acc, avg_loss)
    result = pd.DataFrame([[hnode,lambda_,batsize,avg_acc,avg_loss]],columns=('hnode','lambda_','batsize','acc','loss'))
    results = results.append(result)

results.to_csv('C:/Users/NGV05/Desktop/실습/201027_results_mnist_혼자연습.csv')
results

(60000, 28, 28) (10000, 28, 28)
(60000,) (10000,)
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Assets written to: C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습\10\assets
INFO:tensorflow:Asse

hnode  lambda_  batsize     acc      loss
0     10        1       32  0.9399  0.221646
0    128        1       32  0.9774  0.131369

In [66]:
from tensorflow.keras.models import load_model

model_loaded = load_model('C:/Users/NGV05/Desktop/실습/model_save_mnist_혼자연습/128')
model_loaded.summary()
model_loaded.evaluate(X_test,y_test)

Model: "sequential_79"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_44 (Flatten)         (None, 784)               0         
_________________________________________________________________
dense_155 (Dense)            (None, 128)               100480    
_________________________________________________________________
dense_156 (Dense)            (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
313/313 [==============================] - 0s 634us/step - loss: 0.0774 - acc: 0.1005


[0.07740741968154907, 0.10050000250339508]

In [63]:
model_DNN.weights

[<tf.Variable 'dense_151/kernel:0' shape=(784, 128) dtype=float32, numpy=
 array([[-0.03366144, -0.02520876,  0.06377592, ..., -0.05410007,
         -0.01518001,  0.05515057],
        [ 0.01092017,  0.04454384,  0.03113649, ...,  0.03053663,
         -0.05110561,  0.05212193],
        [-0.0156645 , -0.00519911,  0.04465188, ...,  0.01946015,
         -0.00204886,  0.00914149],
        ...,
        [ 0.00111131, -0.04900872, -0.02368766, ...,  0.03198576,
          0.04317186, -0.06753875],
        [ 0.01100907, -0.053888  , -0.04355162, ...,  0.00986453,
         -0.03995306,  0.00094943],
        [ 0.05337603, -0.03256106, -0.00223531, ...,  0.03959329,
          0.04981921,  0.01402934]], dtype=float32)>,
 <tf.Variable 'dense_151/bias:0' shape=(128,) dtype=float32, numpy=
 array([ 9.43969842e-03, -2.86184140e-02,  2.95759678e-01,  3.90745923e-02,
        -8.88942704e-02, -7.83344209e-02, -1.21176690e-01,  1.13482557e-01,
        -2.67230105e-02,  4.41867501e-01, -6.26856759e-02, -1.6

In [64]:
model_loaded.weights

[<tf.Variable 'dense_151/kernel:0' shape=(784, 128) dtype=float32, numpy=
 array([[-0.03366144, -0.02520876,  0.06377592, ..., -0.05410007,
         -0.01518001,  0.05515057],
        [ 0.01092017,  0.04454384,  0.03113649, ...,  0.03053663,
         -0.05110561,  0.05212193],
        [-0.0156645 , -0.00519911,  0.04465188, ...,  0.01946015,
         -0.00204886,  0.00914149],
        ...,
        [ 0.00111131, -0.04900872, -0.02368766, ...,  0.03198576,
          0.04317186, -0.06753875],
        [ 0.01100907, -0.053888  , -0.04355162, ...,  0.00986453,
         -0.03995306,  0.00094943],
        [ 0.05337603, -0.03256106, -0.00223531, ...,  0.03959329,
          0.04981921,  0.01402934]], dtype=float32)>,
 <tf.Variable 'dense_151/bias:0' shape=(128,) dtype=float32, numpy=
 array([ 0.05277148, -0.02917233,  0.29763073,  0.06408091, -0.08881039,
        -0.07526768, -0.11352294,  0.14141563, -0.02672301,  0.4096014 ,
        -0.0480737 , -0.13055067,  0.16647878,  0.01893221, -0.086460